declare var process: {
  env: {
    EXPO_PUBLIC_AMS_365_SCANDIT_LICENSE_KEY: string;
    EXPO_PUBLIC_APP_ANDROID_ICON: string;
    EXPO_PUBLIC_APP_ANDROID_ICON_BACKGROUNDCOLOR: string;
    EXPO_PUBLIC_APP_ANDROID_SPLASH_BACKGROUNDCOLOR: string;
    EXPO_PUBLIC_APP_ANDROID_SPLASH_IMAGE_WIDTH: string;
    EXPO_PUBLIC_APP_ANDROID_VERSION_CODE: string;
    EXPO_PUBLIC_APP_BUNDLE_IDENTIFIER: string;
    EXPO_PUBLIC_APP_DEFAULT_BACKGROUNDCOLOR: string;
    EXPO_PUBLIC_APP_IOS_BUILD_NUMBER: string;
    EXPO_PUBLIC_APP_IOS_ICON: string;
    EXPO_PUBLIC_APP_IOS_ICON_BACKGROUNDCOLOR: string;
    EXPO_PUBLIC_APP_IOS_SPLASH_BACKGROUNDCOLOR: string;
    EXPO_PUBLIC_APP_IOS_SPLASH_IMAGE_WIDTH: string;
    EXPO_PUBLIC_AMS_MOBILE_SCANDIT_LICENSE_KEY: string;
    EXPO_PUBLIC_APP_NAME: string;
    EXPO_PUBLIC_AMS_PRODUCT_API: string;
    EXPO_PUBLIC_APP_SLUG: string;
    EXPO_PUBLIC_APP_SPLASH_IMAGE: string;
    EXPO_PUBLIC_APP_VERSION: string;
    EXPO_PUBLIC_EXPO_AUTH_SESSION_ANDROID_PATH: string;
    EXPO_PUBLIC_EXPO_AUTH_SESSION_CLIENT_ID: string;
    EXPO_PUBLIC_EXPO_AUTH_SESSION_IOS_NATIVE: string;
    EXPO_PUBLIC_EXPO_AUTH_SESSION_SCOPE_URL: string;
    EXPO_PUBLIC_EXPO_AUTH_SESSION_TENANT_ID: string;
    EXPO_PUBLIC_MOBILE_ENV: string;
  };
};
