declare var process: {
  env: {
    EXPO_PUBLIC_AMS_365_SCANDIT_LICENSE_KEY: string;
    EXPO_PUBLIC_APP_ADAPTIVE_ICON: string;
    EXPO_PUBLIC_APP_ADAPTIVE_ICON_BACKGROUNDCOLOR: string;
    EXPO_PUBLIC_APP_SPLASH_ICON: string;
    EXPO_PUBLIC_APP_SPLASH_ICON_BACKGROUNDCOLOR: string;
    EXPO_PUBLIC_APP_ANDROID_SPLASH_BACKGROUNDCOLOR: string;
    EXPO_PUBLIC_APP_ANDROID_SPLASH_IMAGE_WIDTH: string;
    EXPO_PUBLIC_APP_ANDROID_VERSION_CODE: string;
    EXPO_PUBLIC_APP_BUNDLE_IDENTIFIER: string;
    EXPO_PUBLIC_APP_DEFAULT_BACKGROUNDCOLOR: string;
    EXPO_PUBLIC_APP_IOS_BUILD_NUMBER: string;
    EXPO_PUBLIC_APP_IOS_ICON: string;
    EXPO_PUBLIC_APP_IOS_ICON_BACKGROUNDCOLOR: string;
    EXPO_PUBLIC_APP_IOS_SPLASH_BACKGROUNDCOLOR: string;
    EXPO_PUBLIC_APP_IOS_SPLASH_IMAGE_WIDTH: string;
    EXPO_PUBLIC_AMS_MOBILE_API: string;
    EXPO_PUBLIC_AMS_MOBILE_SCANDIT_LICENSE_KEY: string;
    EXPO_PUBLIC_APP_NAME: string;
    EXPO_PUBLIC_APP_SLUG: string;
    EXPO_PUBLIC_APP_VERSION: string;
    EXPO_PUBLIC_MOBILE_ENV: string;
  };
};
